apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: book-store-backend:latest
        ports:
        - containerPort: 5555
        env:
        - name: PORT
          value: "5555"
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb-service:27017/bookstore?authSource=admin"
        - name: JWT_SECRET
          value: "your-secret-key-here"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 5
          periodSeconds: 5 