apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
  selector:
    app: backend 